import 'package:dio/dio.dart';
import 'package:flutter_workshop/data/post.dart';
import 'package:retrofit/retrofit.dart';

part 'posts_api.g.dart';

/// An HTTP client described with annotations only.
/// The implementation (_PostsApi) is generated by retrofit_generator into posts_api.g.dart.
@RestApi(baseUrl: 'https://jsonplaceholder.typicode.com')
abstract class PostsApi {
  factory PostsApi(Dio dio, {String? baseUrl}) = _PostsApi;

  @GET('/posts')
  Future<List<Post>> getPosts();

  @GET('/posts/{id}')
  Future<Post> getPost(@Path('id') int id);
}
