import 'package:flutter/material.dart';
import 'package:flutter_workshop/common/step_scaffold.dart';
import 'package:flutter_workshop/tasks/task_5/task_post.dart';

/// The server response for GET /posts/1, pasted here so we do not depend on the network.
const taskPostJson = <String, dynamic>{
  'id': 1,
  'userId': 1,
  'title': 'First post',
  'body': 'The body of the first post, which the model cannot see yet.',
};

/// The screen for task 5. The task itself is done in task_post.dart.
class Task5Screen extends StatelessWidget {
  const Task5Screen({super.key});

  @override
  Widget build(BuildContext context) {
    final post = TaskPost.fromJson(taskPostJson);

    return StepScaffold(
      title: 'Task 5',
      solutionPath: '/tasks/5/solution',
      child: ListView(
        padding: const EdgeInsets.all(16),
        children: [
          Text(
            'JSON from the server',
            style: Theme.of(context).textTheme.titleMedium,
          ),
          Text('$taskPostJson'),
          const SizedBox(height: 24),
          Text(
            'Object after TaskPost.fromJson',
            style: Theme.of(context).textTheme.titleMedium,
          ),
          // The toString generated by freezed prints all fields of the model.
          Text('$post'),
        ],
      ),
    );
  }
}
